package Interfaz;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class I_registroAutoController {
	@FXML
	private Label lblCliente;
	@FXML
	private Label lblNroPlaca;
	@FXML
	private Label lblModelo;
	@FXML
	private Label lblMarca;
	@FXML
	private Label lblAño;
	@FXML
	private Label lblHistorial;
	@FXML
	private Label lblGarantia;
	@FXML
	private Label lblcolor;
	@FXML
	private TextField txtNroPlaca;
	@FXML
	private TextField txtMarca;
	@FXML
	private TextField txtModelo;
	@FXML
	private TextField txtAño;
	@FXML
	private TextField txtColor;
	@FXML
	private TextField txtGarantia;
	@FXML
	private TextField txtHistorial;
	@FXML
	private TextField txtCliente;
	@FXML
	private Button btnGuardar;
	@FXML
	private Button btnLimpiar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnGuardar].onAction
	@FXML
	public void btnGuardar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLimpiar].onAction
	@FXML
	public void btnLimpiar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void btnCancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
