package Interfaz;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import Logica.L_clientes;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class I_registroClientesController {
	
	ObservableList<String> tipoDoc = FXCollections.observableArrayList("Documento Nacional de Identidad", "Carnet de Extrangería", "Pasaporte", "Documento de Identidad Extrangero", "Registro Unico de Contribuyente");
		
	@FXML
	private Label lblNombreCliente;
	@FXML
	private Label lblTipoDoc;
	@FXML
	private Label lblNroDoc;
	@FXML
	private Label lblCorreo;
	@FXML
	private Label lblTelefono;
	@FXML
	private TextField txtNombreCliente;
	@FXML
	private TextField txtNroDoc;
	@FXML
	private TextField txtCorreo;
	@FXML
	private TextField txtTelefono;
	@FXML
	private ComboBox<String> cmbxTipoDoc;
	@FXML
	private Button btnRegistrarCliente;
	@FXML
	private Button btnLimpiarFormulario;
	@FXML
	private Button btnSalir;

	@FXML
	private void initialize() {
		cmbxTipoDoc.setValue(tipoDoc.get(0));
		cmbxTipoDoc.setItems(tipoDoc);
	}
	// Event Listener on Button[#btnRegistrarCliente].onAction
	@FXML
	public void btnRegistrarCliente(ActionEvent event) {
		// TODO Autogenerated
		L_clientes.registrarCliente(txtNombreCliente, cmbxTipoDoc, txtNroDoc, txtCorreo, txtTelefono);
	}
	// Event Listener on Button[#btnLimpiarFormulario].onAction
	@FXML
	public void btnLimpiarFormulario(ActionEvent event) {
		// TODO Autogenerated
		txtNombreCliente.setText("");
		txtCorreo.setText("");
		txtNroDoc.setText("");
		txtTelefono.setText("");
	}
	// Event Listener on Button[#btnSalir].onAction
	@FXML
	public void btnSalir(ActionEvent event) {
		salir(event);
	}
	

    public void salir(ActionEvent e) {
		Node source = (Node) e.getSource();
		Stage stage = (Stage)source.getScene().getWindow();
		stage.close();
	}
	
	
	
	
	
}
